# Credit Risk Prediction Project

**Notebook:** 02 - Data Cleaning & Preprocessing

**Author:** Jairus Omondi

**Dataset:** German Credit Dataset

**Project Goal:** Predict whether a loan applicant is likely to be a Good or Bad credit risk using machine learning techniques.

# Data Cleaning & Preprocessing

## Objective

The objective of this notebook is to prepare the German Credit dataset for machine learning by cleaning the data, handling missing values, transforming categorical variables into numerical representations, scaling numerical features where appropriate, and splitting the dataset into training and testing sets.

The preprocessing stage ensures that the dataset is accurate, consistent, and suitable for building reliable credit risk prediction models.

---

## Why Data Preprocessing?

Real-world datasets are rarely ready for machine learning. They often contain missing values, categorical variables, unnecessary columns, and inconsistencies that can negatively affect model performance.

Proper preprocessing improves data quality, enables machine learning algorithms to process the data correctly, and helps produce more reliable and interpretable predictions.

---

## Notebook Workflow

This notebook will cover the following steps:

1. Load the dataset.
2. Inspect the dataset before preprocessing.
3. Remove unnecessary columns.
4. Handle missing values.
5. Encode categorical variables.
6. Scale numerical features.
7. Split the dataset into training and testing sets.
8. Save the processed datasets for model development.

---

## Expected Outcome

By the end of this notebook, the dataset will be fully cleaned and transformed into a machine-learning-ready format. The processed training and testing datasets will then be used in the next notebook to build and evaluate credit risk prediction models.

# 1.Load the Dataset

In [1]:
# Import libraries
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("../data/raw/german_credit_data.csv")

# Display the first five rows
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

## 2.Inspect the Dataset Before Preprocessing

In [2]:
# Check the shape of the dataset
print("Dataset Shape:", df.shape)

Dataset Shape: (1000, 11)

In [3]:
# Display column names
print("Column Names:")
print(df.columns.tolist())

Column Names:
['Unnamed: 0', 'Age', 'Sex', 'Job', 'Housing', 'Saving accounts', 'Checking account', 'Credit amount', 'Duration', 'Purpose', 'Risk']

In [4]:
# Display data types and structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1000 non-null   int64
 1   Age               1000 non-null   int64
 2   Sex               1000 non-null   object
 3   Job               1000 non-null   int64
 4   Housing           1000 non-null   object
 5   Saving accounts   817 non-null    object
 6   Checking account  606 non-null    object
 7   Credit amount     1000 non-null   int64
 8   Duration          1000 non-null   int64
 9   Purpose           1000 non-null   object
 10  Risk              1000 non-null   object
dtypes: int64(5), object(6)
memory usage: 86.1+ KB

In [5]:
# Check missing values
print(df.isnull().sum())

Unnamed: 0            0
Age                   0
Sex                   0
Job                   0
Housing               0
Saving accounts     183
Checking account    394
Credit amount         0
Duration              0
Purpose               0
Risk                  0
dtype: int64

In [6]:
# Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

## 3.Remove Unnecessary Columns

In [7]:
# Remove the unnecessary index column
df = df.drop("Unnamed: 0", axis=1)

In [8]:
# Verify that the column has been removed
print(df.columns.tolist())

['Age', 'Sex', 'Job', 'Housing', 'Saving accounts', 'Checking account', 'Credit amount', 'Duration', 'Purpose', 'Risk']

In [9]:
# Check the new dataset shape
print("New Dataset Shape:", df.shape)

New Dataset Shape: (1000, 10)

## 4.Handling Missing Values

In [10]:
# Count missing values in each column
df.isnull().sum()

Age                   0
Sex                   0
Job                   0
Housing               0
Saving accounts     183
Checking account    394
Credit amount         0
Duration              0
Purpose               0
Risk                  0
dtype: int64

In [11]:
# Calculate percentage of missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage)

Age                  0.0
Sex                  0.0
Job                  0.0
Housing              0.0
Saving accounts     18.3
Checking account    39.4
Credit amount        0.0
Duration             0.0
Purpose              0.0
Risk                 0.0
dtype: float64

In [12]:
# Create a summary table
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_summary

                  Missing Values  Percentage
Age                            0         0.0
Sex                            0         0.0
Job                            0         0.0
Housing                        0         0.0
Saving accounts              183        18.3
Checking account             394        39.4
Credit amount                  0         0.0
Duration                       0         0.0
Purpose                        0         0.0
Risk                           0         0.0

In [13]:
# Replace missing values with 'Unknown'
df["Saving accounts"] = df["Saving accounts"].fillna("Unknown")

df["Checking account"] = df["Checking account"].fillna("Unknown")

In [14]:
# Check missing values again
print(df.isnull().sum())

Age                 0
Sex                 0
Job                 0
Housing             0
Saving accounts     0
Checking account    0
Credit amount       0
Duration            0
Purpose             0
Risk                0
dtype: int64

## 5.Encode Categorical Variables

In [15]:
# Check data types
df.dtypes

Age                  int64
Sex                 object
Job                  int64
Housing             object
Saving accounts     object
Checking account    object
Credit amount        int64
Duration             int64
Purpose             object
Risk                object
dtype: object

### i.Binary encoding

In [16]:
# Binary Encoding
df["Sex"] = df["Sex"].map({
    "female": 0,
    "male": 1
})

df["Risk"] = df["Risk"].map({
    "good": 0,
    "bad": 1
})

### ii.Ordinal encoding

In [17]:
# Ordinal Encoding

saving_order = {
    "Unknown": 0,
    "little": 1,
    "moderate": 2,
    "quite rich": 3,
    "rich": 4
}

checking_order = {
    "Unknown": 0,
    "little": 1,
    "moderate": 2,
    "rich": 3
}

df["Saving accounts"] = df["Saving accounts"].map(saving_order)

df["Checking account"] = df["Checking account"].map(checking_order)

### iii.One-Hot encoding

In [18]:
# One-Hot Encode nominal variables

df = pd.get_dummies(
    df,
    columns=["Housing", "Purpose"],
    drop_first=True
)

In [19]:
print(df["Sex"].unique())

[1 0]

In [20]:
print(df["Risk"].value_counts(dropna=False))

Risk
0    700
1    300
Name: count, dtype: int64

In [21]:
print(df["Saving accounts"].unique())

[0 1 3 4 2]

In [22]:
df.head()

,Age,Sex,Job,Saving accounts,Checking account,Credit amount,Duration,Risk,Housing_own,Housing_rent,Purpose_car,Purpose_domestic appliances,Purpose_education,Purpose_furniture/equipment,Purpose_radio/TV,Purpose_repairs,Purpose_vacation/others
0,67,1,2,0,1,1169,6,0,True,False,False,False,False,False,True,False,False
1,22,0,2,1,2,5951,48,1,True,False,False,False,False,False,True,False,False
2,49,1,1,1,0,2096,12,0,True,False,False,False,True,False,False,False,False
3,45,1,2,1,1,7882,42,0,False,False,False,False,False,True,False,False,False
4,53,1,2,1,1,4870,24,1,False,False,True,False,False,False,False,False,False

In [23]:
df.dtypes

Age                            int64
Sex                            int64
Job                            int64
Saving accounts                int64
Checking account               int64
Credit amount                  int64
Duration                       int64
Risk                           int64
Housing_own                     bool
Housing_rent                    bool
Purpose_car                     bool
Purpose_domestic appliances     bool
Purpose_education               bool
Purpose_furniture/equipment     bool
Purpose_radio/TV                bool
Purpose_repairs                 bool
Purpose_vacation/others         bool
dtype: object

In [24]:
print(df.isnull().sum())

Age                            0
Sex                            0
Job                            0
Saving accounts                0
Checking account               0
Credit amount                  0
Duration                       0
Risk                           0
Housing_own                    0
Housing_rent                   0
Purpose_car                    0
Purpose_domestic appliances    0
Purpose_education              0
Purpose_furniture/equipment    0
Purpose_radio/TV               0
Purpose_repairs                0
Purpose_vacation/others        0
dtype: int64

## 6.Train Test Split

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
# Seperate features and target varriables
# Features (X)
X = df.drop("Risk", axis=1)

# Target variable (y)
y = df["Risk"]

In [27]:
# Check shapes
print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (1000, 16)
Target Shape: (1000,)

In [28]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [29]:
# Verify the split 
print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)

print("Training Target:", y_train.shape)
print("Testing Target:", y_test.shape)

Training Features: (800, 16)
Testing Features: (200, 16)
Training Target: (800,)
Testing Target: (200,)

In [30]:
# Check class distrubution
print("Training Target Distribution:")
print(y_train.value_counts())

print("\nTesting Target Distribution:")
print(y_test.value_counts())

Training Target Distribution:
Risk
0    560
1    240
Name: count, dtype: int64

Testing Target Distribution:
Risk
0    140
1     60
Name: count, dtype: int64

## 7.Feature scaling

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
# Select numerical columns
numerical_columns = [
    "Age",
    "Credit amount",
    "Duration"
]

In [33]:
# Create the scaler
scaler = StandardScaler()

In [34]:
# Fit on training data and transform
X_train[numerical_columns] = scaler.fit_transform(
    X_train[numerical_columns]
)

In [35]:
# Transform the test data
X_test[numerical_columns] = scaler.transform(
    X_test[numerical_columns]
)

In [36]:
# Verify the data
X_train.head()

,Age,Sex,Job,Saving accounts,Checking account,Credit amount,Duration,Housing_own,Housing_rent,Purpose_car,Purpose_domestic appliances,Purpose_education,Purpose_furniture/equipment,Purpose_radio/TV,Purpose_repairs,Purpose_vacation/others
828,1.057784,1,2,0,1,1.925766,1.289592,False,False,True,False,False,False,False,False,False
997,0.242449,1,2,1,0,-0.892853,-0.742595,True,False,False,False,False,False,True,False,False
148,-0.663479,1,2,1,1,0.816433,1.289592,True,False,False,False,False,True,False,False,False
735,-0.572886,0,0,0,2,0.299568,1.289592,True,False,False,True,False,False,False,False,False
130,-1.025850,0,2,0,2,1.982655,2.305686,True,False,True,False,False,False,False,False,False

In [37]:
print(X_train.isnull().sum().sum())
print(X_test.isnull().sum().sum())

0
0

In [38]:
print(y_train.isnull().sum())
print(y_test.isnull().sum())

0
0

In [39]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(800, 16)
(200, 16)
(800,)
(200,)

## 8.Save preprocessed data

In [40]:
# Save training features
X_train.to_csv("../data/processed/X_train.csv", index=False)
# Save testing features
X_test.to_csv("../data/processed/X_test.csv", index=False)
# Save training target
y_train.to_csv("../data/processed/y_train.csv", index=False)
# Save testing target
y_test.to_csv("../data/processed/y_test.csv", index=False)
# Confirm success
print("Processed datasets saved successfully.")

Processed datasets saved successfully.

# Key Findings

## Data Cleaning

The preprocessing phase began by inspecting the dataset to verify its structure and identify potential data quality issues. The unnecessary **Unnamed: 0** column was removed because it represented only row identifiers and provided no predictive value for credit risk classification.

---

## Missing Values

The dataset contained missing values in the **Saving accounts** and **Checking account** variables. Instead of removing these observations, the missing values were replaced with a new category labeled **"Unknown"**. This approach preserved all customer records while avoiding unsupported assumptions about missing financial information.

---

## Categorical Encoding

Different encoding techniques were selected based on the characteristics of each variable:

- **Binary Encoding** was applied to **Sex** and **Risk** because these variables contain only two categories.
- **Ordinal Encoding** was applied to **Saving accounts** and **Checking account** because their categories have a meaningful order (e.g., Little → Moderate → Quite Rich → Rich).
- **One-Hot Encoding** was applied to **Housing** and **Purpose** because these variables are nominal and have no natural ordering.

Selecting the encoding method according to the nature of each variable helps preserve the meaning of the data while preparing it for machine learning.

---

## Train-Test Split

The processed dataset was divided into **80% training data** and **20% testing data** using a stratified train-test split. Stratification ensured that the original class distribution of Good and Bad credit applicants was maintained in both datasets, providing a fair and reliable evaluation of model performance.

---

## Feature Scaling

The numerical features **Age**, **Credit amount**, and **Duration** were standardized using **StandardScaler**. The scaler was fitted only on the training data and then applied to the testing data to prevent data leakage. The **Job** variable was not scaled because it represents categorical job levels rather than continuous numerical measurements.

---

## Processed Dataset

The cleaned and preprocessed training and testing datasets were saved separately for use in model development. Separating preprocessing from model training improves reproducibility, maintains consistency across experiments, and allows multiple machine learning models to be evaluated using the same prepared data.

---

## Conclusion

The preprocessing stage transformed the raw German Credit dataset into a machine-learning-ready dataset while preserving data quality and minimizing information loss. Careful handling of missing values, appropriate encoding techniques, proper train-test splitting, and feature scaling established a reliable foundation for building and evaluating credit risk prediction models in the next stage of the project.